image: node:8

stages:
    - build
    - lint
    - unittests

# build package
build_package:
    stage: build
    script:
        # install packages: jq
        - apt-get update
        - apt-get install -y jq
        # install node dependencies
        - npm install
        # build package artifact
        - npm run build
    tags:
        - cm-official-docker-executor
    artifacts:
        name: package
        paths:
            - node_modules
            - dist
        expire_in: 1 week

# lint package
lint_package:
    stage: lint
    script:
        # linter
        - npm run lint
    tags:
        - cm-official-docker-executor

# run unit tests
unit_tests:
    stage: unittests
    script:
        - npm run test
    tags:
        - cm-official-docker-executor