image: node:8

stages:
    - build
    - lint

# build package
build_package:
    stage: build
    script:
        # install dependencies
        - npm install
    tags:
        - cm-official-docker-executor
    artifacts:
        name: node-modules
        paths:
            - node_modules
        expire_in: 1 week

# lint package
lint_package:
    stage: lint
    script:
        # linter
        - npm run lint
    tags:
        - cm-official-docker-executor
