runtime_parameters:
  - name: AZURE_SERVICE_PRINCIPAL
    type: secret
    secretProvider: 
      type: KeyVault
      environment: azure
      vault: my-keyvault.vault.azure.net
    secretName: my_azure_secret
extension_packages:
    install_operations:
        - extensionType: do
          extensionVersion: 1.5.0
        - extensionType: as3
          extensionVersion: 3.13.0
extension_services:
    service_operations:
      - extensionType: do
        type: url
        value: https://cdn.f5.com/product/cloudsolutions/f5-azure-arm-templates/examples/modules/autoscale_bigip/do.json
      - extensionType: as3
        type: url
        value: https://cdn.f5.com/product/cloudsolutions/f5-azure-arm-templates/examples/modules/autoscale_bigip/as3.json