example_1:
  description: Verifies and installs Automation Toolchain components (DO, AS3) on a local BIG-IP and then configures AS3 from a local declaration file.
  runtime_config:
    runtime_parameters: []
    pre_onboard_enabled:
      - name: provision_rest
        type: inline
        commands:
          - /usr/bin/setdb provision.extramb 500
          - /usr/bin/setdb restjavad.useextramb true
    extension_packages:
      install_operations:
        - extensionType: do
          extensionVersion: 1.12.0
          extensionHash: 95c2b76fb598bbc36fb93a2808f2e90e6c50f7723d27504f3eb2c2850de1f9e1
        - extensionType: as3
          extensionVersion: 3.19.1
          extensionHash: 4477f84d0be2fa8fb551109a237768c365c4d17b44b2665e4eb096f2cfd3c4f1
    extension_services:
      service_operations:
        - extensionType: as3
          type: url
          value: file:///examples/declarations/as3.json
example_2: 
  description: Verifies and installs DO and myIlxApp RPMs from local directories and configures DO from a local declaration file. Install operations with an extensionUrl value that points to a local file may only be installed from the /var/lib/cloud or /var/lib/cloud/icontrollx_installs directories.
  runtime_config:
    runtime_parameters: []
    pre_onboard_enabled:
      - name: provision_rest
        type: inline
        commands:
          - /usr/bin/setdb provision.extramb 500
          - /usr/bin/setdb restjavad.useextramb true
    extension_packages:
      install_operations:
        - extensionType: do
          extensionUrl: file:///var/lib/cloud/icontrollx_installs/f5-declarative-onboarding-1.10.0-2.noarch.rpm
          extensionHash: 95c2b76fb598bbc36fb93a2808f2e90e6c50f7723d27504f3eb2c2850de1f9e1
        - extensionType: ilx
          extensionUrl: file:///var/lib/cloud/myIlxApp.rpm
          extensionVersion: 1.1.0
          extensionVerificationEndpoint: /mgmt/shared/myIlxApp/info
          extensionHash: 4477f84d0be2fa8fb551109a237768c365c4d17b44b2665e4eb096f2cfd3c4f1
    extension_services:
      service_operations:
        - extensionType: do
          type: url
          value: file:///var/lib/cloud/do.json
example_3:
  description: Installs DO and AS3 on a local BIG-IP and renders the Azure service principal secret into an AS3 declaration downloaded from a URL.
  runtime_config:
    runtime_parameters:
      - name: AZURE_SERVICE_PRINCIPAL
        type: secret
        secretProvider: 
          type: KeyVault
          environment: azure
          vaultUrl: https://my-keyvault.vault.azure.net
          secretId: my_azure_secret
    pre_onboard_enabled:
      - name: provision_rest
        type: inline
        commands:
          - /usr/bin/setdb provision.extramb 500
          - /usr/bin/setdb restjavad.useextramb true
    extension_packages:
      install_operations:
        - extensionType: do
          extensionVersion: 1.12.0
        - extensionType: as3
          extensionVersion: 3.19.1
    extension_services:
      service_operations:
        - extensionType: do
          type: url
          value: https://cdn.f5.com/product/cloudsolutions/templates/f5-azure-arm-templates/examples/modules/bigip/autoscale_do.json
        - extensionType: as3
          type: url
          value: file:///examples/declarations/example_3_as3.json
example_4:
  description: Renders secret referenced within DO declaration to configure the admin password on a BIG-IP device in AWS.
  runtime_config:
    runtime_parameters:
      - name: ADMIN_PASS
        type: secret
        secretProvider:
          type: SecretManager
          environment: aws
          version: AWSCURRENT
          secretId: test-document-01
      - name: ROOT_PASS
        type: secret
        secretProvider:
          type: SecretManager
          environment: aws
          version: AWSCURRENT
          secretId: test-document-02
    pre_onboard_enabled:
      - name: provision_rest
        type: inline
        commands:
          - /usr/bin/setdb provision.extramb 500
          - /usr/bin/setdb restjavad.useextramb true
    extension_packages:
      install_operations:
        - extensionType: do
          extensionVersion: 1.12.0
        - extensionType: as3
          extensionVersion: 3.19.1
    extension_services:
      service_operations:
        - extensionType: do
          type: url
          value: file:///examples/declarations/example_4_do.json
example_5:
  description: Renders secret referenced within DO declaration to configure the admin password on a BIG-IP device in GCP.
  runtime_config:
    runtime_parameters:
      - name: ADMIN_PASS
        type: secret
        secretProvider:
          type: SecretsManager
          environment: gcp
          version: latest
          secretId: my-secret-id-01
      - name: ROOT_PASS
        type: secret
        secretProvider:
          type: SecretsManager
          environment: gcp
          version: latest
          secretId: my-secret-id-02
    pre_onboard_enabled:
      - name: provision_rest
        type: inline
        commands:
          - /usr/bin/setdb provision.extramb 500
          - /usr/bin/setdb restjavad.useextramb true
    extension_packages:
      install_operations:
        - extensionType: do
          extensionVersion: 1.12.0
        - extensionType: as3
          extensionVersion: 3.19.1
    extension_services:
      service_operations:
        - extensionType: do
          type: url
          value: file:///examples/declarations/example_5_do.json
example_6:
  description: Replaces variables used within DO declaration with properties from instance metadata to configure hostname and self IP addresses on BIGIP device.
  runtime_config:
    runtime_parameters:
      - name: HOST_NAME
        type: metadata
        metadataProvider:
          environment: aws
          type: compute
          field: hostname
      - name: SELF_IP_EXTERNAL
        type: metadata
        metadataProvider:
          environment: aws
          type: network
          field: local-ipv4s
          index: 1
      - name: SELF_IP_INTERNAL
        type: metadata
        metadataProvider:
          environment: aws
          type: network
          field: local-ipv4s
          index: 2
      - name: DEFAULT_ROUTE
        type: metadata
        metadataProvider:
          environment: aws
          type: network
          field: subnet-ipv4-cidr-block
          index: 1
    pre_onboard_enabled:
      - name: provision_rest
        type: inline
        commands:
          - /usr/bin/setdb provision.extramb 500
          - /usr/bin/setdb restjavad.useextramb true
    extension_packages:
      install_operations:
        - extensionType: do
          extensionVersion: 1.12.0
        - extensionType: as3
          extensionVersion: 3.19.1
    extension_services:
      service_operations:
        - extensionType: do
          type: url
          value: file:///examples/declarations/example_6_do.json
example_7:
  description: Installs AS3 and DO and uses an inline AS3 declaration to setup the BIG-IP.
  runtime_config:
    runtime_parameters: []
    pre_onboard_enabled:
      - name: provision_rest
        type: inline
        commands:
          - /usr/bin/setdb provision.extramb 500
          - /usr/bin/setdb restjavad.useextramb true
    extension_packages:
      install_operations:
        - extensionType: do
          extensionVersion: 1.5.0
        - extensionType: as3
          extensionVersion: 3.13.0
    extension_services:
      service_operations:
        - extensionType: as3
          type: inline
          value: 
            class: AS3
            action: deploy
            persist: true
            declaration:
              class: ADC
              schemaVersion: 3.0.0
              id: urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d
              label: Sample 1
              remark: Simple HTTP Service with Round-Robin Load Balancing
              Sample_01:
                class: Tenant
                A1:
                  class: Application
                  template: http
                  serviceMain:
                    class: Service_HTTP
                    virtualAddresses:
                    - 10.0.1.10
                    pool: web_pool
                  web_pool:
                    class: Pool
                    monitors:
                    - http
                    members:
                    - servicePort: 80
                      serverAddresses:
                      - 192.0.1.10
                      - 192.0.1.11
example_8:
  description: Using runtime parameters with inline Automation Toolchain declarations.
  runtime_config:
    runtime_parameters:
      - name: SCHEMA_VERSION
        type: static
        value: 3.0.0
      - name: HOST_NAME
        type: static
        value: bigip1.example.com
    pre_onboard_enabled:
      - name: provision_rest
        type: inline
        commands:
          - /usr/bin/setdb provision.extramb 500
          - /usr/bin/setdb restjavad.useextramb true
    extension_packages:
      install_operations:
        - extensionType: do
          extensionVersion: 1.5.0
        - extensionType: as3
          extensionVersion: 3.13.0
    extension_services:
      service_operations:
        - extensionType: do
          type: inline
          value: 
            schemaVersion: "{{{ SCHEMA_VERSION }}}"
            class: Device
            async: true
            label: my BIG-IP declaration for declarative onboarding
            Common:
              class: Tenant
              hostname: "{{{ HOST_NAME }}}"
              myDns:
                class: DNS
                nameServers:
                - 8.8.8.8
              myNtp:
                class: NTP
                servers:
                - 0.pool.ntp.org
                timezone: UTC
              myProvisioning:
                class: Provision
                ltm: nominal
                asm: nominal
              dbvars:
                class: DbVariables
                provision.extramb: 500
                restjavad.useextramb: true
        - extensionType: as3
          type: inline
          value:
            class: AS3
            action: deploy
            persist: true
            declaration:
              class: ADC
              schemaVersion: "{{{ SCHEMA_VERSION }}}"
              label: Sample 1
              remark: Simple HTTP Service with Round-Robin Load Balancing
              Sample_01:
                class: Tenant
                A1:
                  class: Application
                  template: http
                  serviceMain:
                    class: Service_HTTP
                    virtualAddresses:
                    - 10.0.1.10
                    pool: web_pool
                  web_pool:
                    class: Pool
                    monitors:
                    - http
                    members:
                    - servicePort: 80
                      serverAddresses:
                      - 192.0.1.10
                      - 192.0.1.11
example_9:
  description: Using custom pre-onboard and post-onboard commands.
  runtime_config:
    runtime_parameters: []
    pre_onboard_enabled:
      - name: example_inline_command
        type: inline
        commands:
          - touch /tmp/pre_onboard_script.sh
          - chmod 777 /tmp/pre_onboard_script.sh
          - echo "touch /tmp/create_by_autogenerated_pre_local" > /tmp/pre_onboard_script.sh
      - name: provision_rest
        type: inline
        commands:
          - /usr/bin/setdb provision.extramb 500
          - /usr/bin/setdb restjavad.useextramb true
      - name: example_local_exec
        type: file
        commands:
          - /tmp/pre_onboard_script.sh
      - name: example_remote_exec
        type: url
        commands:
          - https://the-delivery-location.com/remote_pre_onboard.sh
    post_onboard_enabled:
      - name: example_inline_command
        type: inline
        commands:
          - touch /tmp/post_onboard_script.sh
          - chmod 777 /tmp/post_onboard_script.sh
          - echo "touch /tmp/create_by_autogenerated_post_local" > /tmp/post_onboard_script.sh
      - name: example_local_exec
        type: file
        commands:
          - /tmp/post_onboard_script.sh
      - name: example_remote_exec
        type: url
        commands:
          - https://the-delivery-location.com/remote_post_onboard.sh
    extension_packages:
      install_operations:
        - extensionType: do
          extensionVersion: 1.12.0
        - extensionType: as3
          extensionVersion: 3.19.1
    extension_services:
      service_operations: []
example_10: 
  description: Sending a customized webhook on completion.
  runtime_config:
    runtime_parameters: []
    pre_onboard_enabled:
      - name: provision_rest
        type: inline
        commands:
          - /usr/bin/setdb provision.extramb 500
          - /usr/bin/setdb restjavad.useextramb true
    extension_packages:
      install_operations:
        - extensionType: do
          extensionVersion: 1.12.0
        - extensionType: as3
          extensionVersion: 3.19.1
    extension_services:
      service_operations: []
    post_onboard_enabled: []
    post_hook:
      - name: example_webhook
        type: webhook
        url: https://webhook.site
        verifyTls: true
        properties:
          optionalKey1: optional_value1
          optionalKey2: optional_value2
example_11:
  description: 'Overrides default certificate validation/verification using the verifyTls parameter. The following attributes support verifyTls: pre_onboard_enabled, post_onboard_enabled, extension_packages.install_operations, extension_services.service_operations, and post_hook.'
  runtime_config:
    runtime_parameters: []
    pre_onboard_enabled:
      - name: example_remote_exec
        type: url
        commands:
          - https://ak-metadata-package-poc.s3.amazonaws.com/remote_pre_onboard.sh
      - name: provision_rest
        type: inline
        commands:
          - /usr/bin/setdb provision.extramb 500
          - /usr/bin/setdb restjavad.useextramb true
    post_onboard_enabled:
      - name: example_inline_command
        type: inline
        commands:
          - touch /tmp/post_onboard_script.sh
          - chmod 777 /tmp/post_onboard_script.sh
          - echo "touch /tmp/created_by_autogenerated_post_local" > /tmp/post_onboard_script.sh
      - name: example_local_exec
        type: file
        commands:
          - /tmp/post_onboard_script.sh
      - name: example_remote_exec
        type: url
        commands:
          - https://ak-metadata-package-poc.s3.amazonaws.com/remote_post_onboard.sh
        verifyTls: false
      - name: example_remote_exec
        type: url
        commands:
          - https://ak-metadata-package-poc.s3.amazonaws.com/remote_post_onboard.sh
    extension_packages:
      install_operations:
        - extensionType: do
          extensionVersion: 1.10.0
        - extensionType: as3
          extensionVersion: 3.20.0
          verifyTls: false
          extensionUrl: https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.20.0/f5-appsvcs-3.20.0-3.noarch.rpm
          extensionHash: ba2db6e1c57d2ce6f0ca20876c820555ffc38dd0a714952b4266c4daf959d987
        - extensionType: ilx
          extensionUrl: file:///var/lib/cloud/icontrollx_installs/f5-appsvcs-templates-1.1.0-1.noarch.rpm
          extensionVersion: 1.1.0
          extensionVerificationEndpoint: /mgmt/shared/fast/info
    extension_services:
      service_operations:
        - extensionType: do
          type: url
          value: https://cdn.f5.com/product/cloudsolutions/declarations/autoscale-waf/autoscale_do_payg.json
          verifyTls: false
        - extensionType: as3
          type: url
          value: https://cdn.f5.com/product/cloudsolutions/templates/f5-azure-arm-templates/examples/modules/bigip/autoscale_as3.json
    post_hook:
      - name: example_webhook
        type: webhook
        verifyTls: false
        url: https://postman-echo.com/post
        properties:
          optionalKey1: optional_value1
          optionalKey2: optional_value2