---
runtime_parameters:  
  - name: GCP_SECRET
    type: secret
    secretProvider: 
      type: SecretManager
      environment: gcp
      project: f5-7656-pdsoleng-dev
    secretName: my_gcp_secret
  - name: GCP_SECRET_ALT
    type: secret
    secretProvider:
       type: default
    secretName: my_gcp_secret_alt
  - name: AWS_SECRET
    type: secret
    secretProvider:
       type: SecretsManager
       environment: aws
       region: us-east-1
    secretName: my_aws_secret
  - name: AWS_SECRET_ALT
    type: secret
    secretProvider:
       type: default
    secretName: my_aws_secret_alt
  - name: AZURE_SECRET
    type: secret
    secretProvider: 
      type: KeyVault
      environment: azure
      vault: my-keyvault.vault.azure.net
    secretName: my_azure_secret
  - name: AZURE_SECRET_ALT
    type: secret
    secretProvider:
       type: default
    secretName: my_azure_secret_alt
  - name: VAULT_SECRET
    type: secret
    secretProvider: 
      type: hashicorpVault
      namespace: ns1
      token: f3b09679-3001-009d-2b80-9c306ab81aa6
    secretName: my_vault_secret
  - name: HOST_NAME
    type: string
    value: bigip1.example.com
  - name: LICENSE_KEY
    type: string
    value: NEZXD-VIGHH-BLFAQ-QRYQH-RRVEEHO
extension_packages:
    install_operations:
        - extensionType: do
          extensionVersion: 1.5.0
        - extensionType: as3
          extensionVersion: 3.13.0
        - extensionType: ts
          extensionVersion: 1.9.0
        - extensionType: cf
          extensionVersion: 1.0.0
extension_services:
    service_operations:
      - extensionType: do
        type: url
        value: https://cdn.f5.com/product/cloudsolutions/templates/f5-azure-arm-templates/examples/modules/autoscale_bigip/do.json
      - extensionType: as3
        type: url
        value: https://cdn.f5.com/product/cloudsolutions/templates/f5-azure-arm-templates/examples/modules/autoscale_bigip/as3.json
      - extensionType: ts
        type: file
        value: ./examples/declarations/ts.json
      - extensionType: cf
        type: file
        value: ./examples/declarations/cf.json